# Generated by Django 4.2.2 on 2023-06-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
