# Generated by Django 4.2.2 on 2023-06-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_address_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
        ),
    ]
