# Generated by Django 4.2.2 on 2023-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_address_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
    ]
